make_dataset:
  test_size: 0.1
  random_state: 10

data_preprocessing:
  percentiles:
    - 0.002
    - 0.998

#train_model:
  #random_forest_regressor:
    #n_estimators: 100    # Change the number of estimators to a higher number to get better results
    #max_depth: 10
    #verbose: 2
    #n_jobs: -1

train_model:
  xgboost:
    n_estimators: 100       # Number of boosting rounds (trees)
    max_depth: 10            # Maximum depth of trees
    learning_rate: 0.1      # Step size shrinkage to prevent overfitting
    verbosity: 1            # Verbosity level (0 = silent, 1 = warning, 2 = info, 3 = debug)
    n_jobs: -1              # Number of parallel jobs to run (-1 means use all processors)